<h2>List Items</h2>
<!-- TODO: Change this from records -->
<?php if (count($this->sites)): ?>
<div id="records">
  <form method="post" action="<?php echo $this->url(array(), 'admin-catalog-delete'); ?>">
    <table>
      <tr>
        <td></td>    
        <td class="key">
          Item ID
        </td>
        <td class="key">
          Title
        </td>
        <td class="key">
          Denomination
        </td>
        <td class="key">
          Country
        </td>
        <td class="key">
          Grade
        </td>
        <td class="key">
          Year
        </td>    
        <td></td>    
        <td></td>    
      </tr>
      <?php foreach ($this->sites as $site):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?php echo $site->id; ?>" style="width:2px" /></td>
        <td><?php echo $this->escape($site->id); ?></td>
        <td><?php echo $this->escape($site->title); ?></td>
        <td><?php echo $this->escape($site->language); ?></td>
        <td><?php echo $this->escape($site->keyword); ?></td>
        <td><?php echo $this->escape($site->desc); ?></td>
        <td><?php echo $this->escape($site->directory); ?></td>    
      </tr>  
      <?php endforeach; ?>
      <tr>
        <td colspan="9"><input type="submit" name="submit" style="width:150px" value="Delete Selected" /></td>
      </tr>    
    </table>
  </form>
</div>

<?php else: ?>
No records found - hab nüscht gefunden!!
<?php endif; ?>
